### ISSUE TITLE
Rendering issue under Windows 

### ISSUE THREAD

**Issue by amishrabbit** [STIXProject/stix-viz#19] opened 2018-06-25 16:50 UTC
Hey there. I've followed the instructions on the readme about how to build a Windows executable from the node.js files in the repository, and I've managed to build an executable that functions under Windows 7/64 and Windows 10/64, but regardless, there appears to be a bug in the UI that shows up under this platform.

The bug is that the visualization only appears within a field of approximately 375 by 325 pixels within the upper left corner of the main application window, no matter how large the display size or whether the window is maximized. When I double click nodes, the expanded nodes often slide out of view to the right edge of this small viewing area.

I've used a sample XML file retrieved from https://www.us-cert.gov/sites/default/files/publications/MAR-10135536-12_WHITE_stix.xml to test this.

The specific build of this StixViz.exe is on Virustotal here: https://www.virustotal.com/en/file/723fa79eb54ef027ec262eb2954e8147ee1e0c65053130e9e8fa360959d685d8/analysis/1529939782/

I'm trying to attach a screenshot to this ticket but the window repeatedly just tells me "Something went really wrong and we can't process that file" so I'll try to reply to this ticket with the screenshot later.

Thank you!

**Comment by gtback** [comment] 2018-06-25 20:21
Here is a screenshot of the issue:
![stixview-gfx-bug](https://user-images.githubusercontent.com/1045796/41873711-67de5328-788b-11e8-8844-268a53368fba.jpg)

**Comment by gtback** [comment] 2018-06-25 20:34
Thanks for reporting this, @amishrabbit . As I'm sure you've noticed, this repository hasn't been updated in a long (!) time. It's hard for me to know if it's because some of the dependencies are out of date, or if it's an incompatibility with newer versions of Windows/Java/Node, etc. 

Are you able to provide more information about the exact versions of things you're using to build it? That would give us the best chance of being able to reproduce it.

**Comment by amishrabbit** [comment] 2018-06-25 21:12
The version of Node I am using is named:
nwjs-v0.31.3-win-x64.zip
from
https://dl.nwjs.io/v0.31.3/nwjs-v0.31.3-win-x64.zip

And it's literally just that and the repository. I tested this on Windows 10/64 build 1709 (bare metal) and Windows 7/64 build 7601 (SP1) (Virtual machine) and both platforms exhibit the same visual glitch.

**Comment by amishrabbit** [comment] 2018-07-06 20:32
Hey Greg. Just checking back to see whether this is sufficient information or if you needed me to try anything else. Let me know. Thanks!

**Comment by gtback** [comment] 2018-07-11 17:02
I don't have a Windows machine to try this on, but I think @slubar is going to take a look.

**Comment by amishrabbit** [comment] 2018-07-11 17:22
OK, thank you.

**Comment by gtback** [comment] 2018-07-13 13:27
Hi @amishrabbit . @slubar was able to build a version of `master` that didn't have that issue. I uploaded it as StixViz.exe under [this release](https://github.com/STIXProject/stix-viz/releases/tag/v1.0.7a). There weren't any changes that needed to be made, so it's possible there was a file missing from the .zip file used with node-webkit. 

Let me know if the uploaded exe doesn't work for you. If it does, then we can go ahead and close this issue.

**Comment by gtback** [comment] 2018-07-16 20:54
I'm going to close this, but if you're still having problems, let us know @amishrabbit . 

Thanks for reporting the issue.

**Closed as completed by gtback** 2018-07-16 20:54 UTC
